services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PPOSTGRES_MULTIPLE_DATABASES: "comments_db,polls_db,users_db,blog_db"
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5673"
      - "15673:15673"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  auth-service:
    build: ./auth-service
    ports:
      - "3050:3050"
    depends_on:
      - postgres
      - rabbitmq

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
volumes:
  postgres_data:
